modified sonarscanner execution

diff --git a/EmployeeProject/Dockerfile b/EmployeeProject/Dockerfile
--- a/EmployeeProject/Dockerfile
+++ b/EmployeeProject/Dockerfile
@@ -10,7 +10,7 @@ FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
 WORKDIR /src
 COPY ["EmployeeProject.csproj", "EmployeeProject/"]
 
-ARG boolvalue=no
+ARG SONAR=true
 RUN dotnet restore "EmployeeProject/EmployeeProject.csproj"
 COPY  . "EmployeeProject/"
 WORKDIR "/src/EmployeeProject"
@@ -23,17 +23,23 @@ RUN pwd \
     
 RUN dotnet tool run swagger tofile --output swagger.json bin/Debug/netcoreapp3.1/EmployeeProject.dll v1
 
-RUN if [ "$boolvalue" = "Yes" ] ; then dotnet tool install -g dotnet-sonarscanner && dotnet tool install -g dotnet-reportgenerator-globaltool \
+RUN if [ "$SONAR" = true ] ; then \
+    apt-get update && apt-get install -y openjdk-11-jdk \
+    && dotnet tool install -g dotnet-sonarscanner \
+    && dotnet tool install -g dotnet-reportgenerator-globaltool \
     && export PATH="${PATH}:/root/.dotnet/tools" \
     && dotnet sonarscanner begin \
-	/k:testimplementation \
-        /name:EmployeeProject \
-        /d:sonar.host.url=http://3.109.121.132:9000/ \
-        /d:sonar.branch.name=dindlocaldb \
-	/d:sonar.coverageReportPaths="coverage/SonarQube.xml" \
-    && dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage ; exit 0 \
-    && reportgenerator "-reports:./coverage/*/coverage.cobertura.xml" "-targetdir:coverage" "-reporttypes:SonarQube" ; exit 0 \
-    && dotnet sonarscanner end; fi
+    /k:EmployeeProject \
+    /d:sonar.host.url=http://3.109.121.132:9000/ \
+    /d:sonar.branch.name=dindlocaldb \
+    /d:sonar.coverageReportPaths="coverage/SonarQube.xml" \
+    && dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage || echo "Tests Failed" \
+    && reportgenerator "-reports:./coverage/*/coverage.cobertura.xml" "-targetdir:coverage" "-reporttypes:SonarQube"  || echo "Reportgenerator Failed" \
+    && dotnet sonarscanner end; \
+    else echo "Sonarscanner Stage Skipped"; \
+    fi
+
+RUN ls -lR
 
 
 FROM build AS publish
